/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { StakingModule__factory } from "./StakingModule__factory";
export { Token__factory } from "./Token__factory";
